### ISSUE TITLE
Which is correct?

### ISSUE THREAD

**Issue by higuuu** [aws-samples/aws-cdk-v2-bootstrap#1]
May be, I found typo in [readme](https://github.com/aws-samples/aws-cdk-v2-bootstrap/blob/main/README.md#pre-requisites).

There,  It's written `pyyaml`.

> Install the pyyaml lib, pip install pyyaml

But in [requirements.txt](https://github.com/aws-samples/aws-cdk-v2-bootstrap/blob/main/requirements.txt), It's written `pyaml`.

Which is correct?

**Comment by Lazzaretti** [comment]
pyaml is a "[PyYAML](http://pyyaml.org/)-based python module to produce a bit more pretty and human-readable YAML-serialized data."
So pyaml extens PyYAML.

It works with PyYAML for me, so **I would just use PyYAML**.
